services:
  app:
    build:
      context: .
    container_name: lumen_app
    volumes:
      - .:/var/www
    working_dir: /var/www
    networks:
      - lumen

  nginx:
    image: nginx:alpine
    container_name: lumen_nginx
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - lumen

  db:
    image: mysql:5.7
    container_name: lumen_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lumen
      MYSQL_USER: lumen
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - lumen

networks:
  lumen:

volumes:
  dbdata:
